image: registry.suse.de/home/bbobrov/registry/containers/harbor/harbor-redis-operator
tag: 1.0.0
pullPolicy: Always
containerName: redisoperator
podAnnotations: {}
resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 100m
    memory: 50Mi
rbac:
  install: true
  apiVersion: v1
  imagePullSecrets: []
monitoring:
  enabled: false
  serviceMonitor: false
  serviceAnnotations: {}
  prometheus:
    name: unknown
